# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Utility' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Utility
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'CryptoSwift'

  target 'iOS_UtilityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_UtilityUITests' do
    # Pods for testing
  end

end
